# Prometheus Configuration for SyncBoard Production Monitoring
# Comprehensive monitoring setup for high-availability deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'syncboard-prod'
    environment: 'production'

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # =============================================================================
  # SyncBoard Application Metrics
  # =============================================================================
  - job_name: 'syncboard-app'
    static_configs:
      - targets: ['syncboard:5000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'syncboard-app'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # Nginx Metrics
  # =============================================================================
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'nginx'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # PostgreSQL Metrics
  # =============================================================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'postgres'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # Redis Metrics
  # =============================================================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'redis'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # Node Exporter (System Metrics)
  # =============================================================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'node-exporter'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # cAdvisor (Container Metrics)
  # =============================================================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'cadvisor'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # Elasticsearch Metrics
  # =============================================================================
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'elasticsearch'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # Grafana Metrics
  # =============================================================================
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'grafana'
      - target_label: environment
        replacement: 'production'

  # =============================================================================
  # Blackbox Exporter (Uptime Monitoring)
  # =============================================================================
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://syncboard:5000/health
        - http://nginx:80/health
        - http://grafana:3000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # =============================================================================
  # Custom Application Metrics
  # =============================================================================
  - job_name: 'syncboard-custom'
    static_configs:
      - targets: ['syncboard:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    
    # Relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'
      - target_label: job
        replacement: 'syncboard-custom'
      - target_label: environment
        replacement: 'production'

# =============================================================================
# Storage Configuration
# =============================================================================
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# =============================================================================
# Remote Write Configuration (Optional)
# =============================================================================
# remote_write:
#   - url: "https://your-remote-storage.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'syncboard_.*'
#         action: keep

# =============================================================================
# Remote Read Configuration (Optional)
# =============================================================================
# remote_read:
#   - url: "https://your-remote-storage.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"